/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package starbank.Vista;

import starbank.Cajero;
import starbank.ClienteEmpresa;
import starbank.ClientePersona;

/**
 *
 * @author YEISON
 */
public class MenuStarBank extends javax.swing.JFrame {

    /**
     * Creates new form MenuStarBank
     */
    public static String idCliente;
    public static String tipoCliente;
    public static boolean iniciarSesion = false;//Esta variable le indica a la clase MenuCliente si debe venir a esta clase y tomar el id y tipo de cliente
    //o si debe ir a tomar estos datos a la clase CrearCliente
    //Si es false, entonces la persona no está registrada y deberá registrarse. Si es verdadera, entonces la persona si está registrada y deberá traerInformacionCliente sesion.

    public MenuStarBank() {
        initComponents();
        this.setResizable(false);//Para que no se pueda cambiar el tamaño de la ventana
        Cajero.cajero.traerJson();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonCrearCliente = new javax.swing.JButton();
        BotonIniciarSesionCliente = new javax.swing.JButton();
        TextFieldId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxTipoCliente = new javax.swing.JComboBox<>();
        TextFieldContraseña = new javax.swing.JTextField();
        LabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        BotonCrearCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        BotonCrearCliente.setText("Crear Cliente");
        BotonCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearClienteActionPerformed(evt);
            }
        });

        BotonIniciarSesionCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BotonIniciarSesionCliente.setText("Iniciar Sesion Cliente");
        BotonIniciarSesionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarSesionClienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setText("INICIAR SESION");

        ComboBoxTipoCliente.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ComboBoxTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona", "Empresa" }));
        ComboBoxTipoCliente.setSelectedItem(null);

        LabelError.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonCrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BotonIniciarSesionCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                .addComponent(TextFieldId, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextFieldContraseña, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(ComboBoxTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(LabelError)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonCrearCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(95, 95, 95)
                .addComponent(TextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TextFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(ComboBoxTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(BotonIniciarSesionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelError)
                .addGap(62, 135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearClienteActionPerformed
        CrearCliente ventanaCrearCliente = new CrearCliente();
        ventanaCrearCliente.setVisible(true);
    }//GEN-LAST:event_BotonCrearClienteActionPerformed

//Comprueba que el cliente sí exista y si es así comprueba la contraseña. Si todo es correcto lo lleva a MenuCliente
    private void BotonIniciarSesionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarSesionClienteActionPerformed

        //Mira el tipo de Cliente para buscarlo en la lista de Personas o Empresas
        if (ComboBoxTipoCliente.getSelectedItem().toString().equalsIgnoreCase("Persona"))
        {
            //Busca el id dentro de la lista de clientes
            ClientePersona persona = Cajero.cajero.traerClientePersona(TextFieldId.getText());

            //Si persona es nulo significa que el cliente no está registrado y manda un mensaje para que se registre
            if (persona == null)
            {
                LabelError.setText("Cliente no registrado");
                System.out.println("Cliente Nulo");
            } else {
                //Si el cliente si está registrado, entonces comprueba la contraseña
                if (TextFieldContraseña.getText().equalsIgnoreCase(persona.getContraseña()))
                {
                    this.idCliente = TextFieldId.getText();
                    this.tipoCliente = ComboBoxTipoCliente.getSelectedItem().toString();
                    this.iniciarSesion = true;
                    
                    //Va a la clase MenuCliente, como traerInformacionCliente sesion en true, vendrá a está clase a tomar los valores de id y tipoCliente
                    MenuCliente menuCliente = new MenuCliente();
                    menuCliente.setVisible(true);

                } else {
                    System.out.println("Contraseña persona incorreta");
                }
            }

        } else if (ComboBoxTipoCliente.getSelectedItem().toString().equalsIgnoreCase("Empresa")){
            ClienteEmpresa empresa = Cajero.cajero.traerClienteEmpresa(TextFieldId.getText());

            if (empresa == null) 
            {
                LabelError.setText("Cliente no registrado");
                System.out.println("Cliente Nulo");
            } else {
                if (TextFieldContraseña.getText().equalsIgnoreCase(empresa.getContraseña())) 
                {
                    this.idCliente = TextFieldId.getText();
                    this.tipoCliente = ComboBoxTipoCliente.getSelectedItem().toString();
                    this.iniciarSesion = true;

                    MenuCliente menuCliente = new MenuCliente();
                    menuCliente.setVisible(true);
                } else {
                    System.out.println("Contraseña empresa incorreta");
                }
            }
        } else {
            System.out.println("Ninguno seleccionado");
        }
    }//GEN-LAST:event_BotonIniciarSesionClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuStarBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuStarBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuStarBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuStarBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuStarBank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCrearCliente;
    private javax.swing.JButton BotonIniciarSesionCliente;
    private javax.swing.JComboBox<String> ComboBoxTipoCliente;
    private javax.swing.JLabel LabelError;
    private javax.swing.JTextField TextFieldContraseña;
    private javax.swing.JTextField TextFieldId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
