/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package starbank.Vista;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import starbank.CuentaCorriente;
import starbank.CuentaDeAhorros;
import static starbank.Vista.InformacionCuenta.cuentaCorriente;
import static starbank.Vista.InformacionCuenta.cuentaDeAhorros;

/**
 *
 * @author YEISON
 */
public class Operaciones extends javax.swing.JFrame {

    /**
     * Creates new form Desactivar
     */
    DefaultTableModel modelo;
    CuentaCorriente cuentaCorriente;
    CuentaDeAhorros cuentaDeAhorros;

    public Operaciones() {
        initComponents();
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        modelo = (DefaultTableModel) TablaOperaciones.getModel();
        ArrayList<String> listaOperaciones = new ArrayList<String>();

        if (InformacionCuenta.tipoCuenta.equalsIgnoreCase("Corriente"))
        {
            this.cuentaCorriente = InformacionCuenta.cuentaCorriente;
            listaOperaciones = cuentaCorriente.getListaOperaciones();

        } else if (InformacionCuenta.tipoCuenta.equalsIgnoreCase("DeAhorros")) 
        {
            this.cuentaDeAhorros = InformacionCuenta.cuentaDeAhorros;
            listaOperaciones = cuentaDeAhorros.getListaOperaciones();
        }
        /*listaOperaciones guarda las operaciones en un string con los nombres, seguido del valor.
        Cada operacion se guarda en un String, y cada una tiene nombre, fecha y valor.
        Y al final del string, y entre nombre, fecha y valor, hay un '\n', para separlos.
        Ejm: "Operacion: retirar\nFecha: 5 de junio\nValor a retirar: 20000\n"
        Lo que se hace abajo es guardar todo el string en texto.
        La primera vez, se guarda en texto2 desde el principio hasta la primera \n,
        pero las otras dos veces, se guarda desde la posicion que tenia la ultima \n hasta la proxima \n.
        Y en textoCortado se recorta el nombre, para que solo quede el valor, en el ejemplo de arriba se 
        quitaria "Operacion: ", "Fecha: " y "Valor a retirar: ", y quedarian solo los valores, así
        retirar, 5 de junio y 20000.
        Tambien, antes de que se acabe el segundo for, se reemplaza el "\n" por un espacio " ", pero se 
        guarda su posicion en K para que en la otra vuelta sepa que debe empezar desde allí*/
        
        String texto = "";/*Se guardan los objetos de listaOperaciones*/
        String texto2;/*Guarda un substring de texto*/
        for (int i = 0; i < listaOperaciones.size(); i++) 
        {
            modelo.addRow(new Object[]{"", "", ""});
            texto = listaOperaciones.get(i);
            int k = 0;/*Guarda la posicion del /n*/
            String textoCortado = "";
            for (int j = 0; j < 3; j++)
            {
                texto2 = texto.substring(k, texto.indexOf("\n"));
                if (j == 0){textoCortado = texto2.replace("Operacion: ", "");}
                if (j == 1){textoCortado = texto2.replace("Fecha: ", "");}
                if (j == 2) {textoCortado = texto2.replace("Valor: ", "");}

                modelo.setValueAt(textoCortado, i, j);
                k = texto.indexOf("\n");
                texto = texto.replaceFirst("\n", " ");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaOperaciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        TablaOperaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nombre Operacion", "Fecha", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaOperaciones);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setText("Lista de Operaciones sobre la cuenta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(245, 245, 245))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaOperaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
